#!/bin/bash
DIR=$(dirname $(dirname $(realpath $0)))
TARGET=$(dirname $DIR)/akmaljp.github.io/DriveMaru/coverage

cd $DIR

rm -rf $TARGET
phpunit -d memory_limit=600M --exclude-group needs-js --coverage-html $TARGET

REGEXP=s/`echo $(dirname $(dirname $DIR)) | sed -e 's/\\//\\\\\//g'`//g
sed -i $REGEXP $TARGET/*.html

SHA1=`git rev-parse HEAD`
REGEXP='s/(<small>Generated by .*? at )[^.]+/\1<a href="https:\/\/github.com\/akmaljp\/DriveMaru\/tree\/'$SHA1'">'$SHA1'<\/a>/'
sed -i -r "$REGEXP" $TARGET/*.html

touch $TARGET/.nojekyll